Vagrant.configure(2) do |config|

  config.vm.box = "box-cutter/ubuntu1404-desktop"

  config.vm.box_check_update = false 

  config.vm.provider "virtualbox" do |vb| 

  vb.gui = true  

  vb.memory = "2048"
  
  vb.name = "FSE-2013-aPET1"

end


config.vm.provision "shell", inline: <<-SHELL

  add-apt-repository -y ppa:webupd8team/java

  apt-get update

  echo "oracle-java8-installer shared/accepted-oracle-license-v1-1 select true" | sudo debconf-set-selections

  apt-get install -y oracle-java8-installer

  export JAVA_HOME=/usr/lib/jvm/java-8-oracle

  source /etc/environment

  apt-get update 

  cd Desktop

  wget -O desktop_folder.tar.gz https://github.com/SoftwareEngineeringToolDemos/FSE-2013-aPET/raw/master/build-vm/vm-contents/desktop_folder.tar.gz

  tar -xvzf desktop_folder.tar.gz

  mv desktop_folder/* .

  rm desktop_folder.tar.gz

  rmdir desktop_folder

  wget -O apet_workspace.tar.gz https://github.com/SoftwareEngineeringToolDemos/FSE-2013-aPET/raw/master/build-vm/vm-contents/apet_workspace.tar.gz

  tar -xvzf apet_workspace.tar.gz

  rm apet_workspace.tar.gz

  wget -O eclipse.tar.gz https://googledrive.com/host/0B49VkAq-KMteMy1YQUxwODVhTGM/eclipse.tar.gz 

  tar -zxvf eclipse.tar.gz

  rm eclipse.tar.gz
 
  ln -s eclipse/eclipse /usr/bin/eclipse

  # Create an application launcher for Eclipse (to launch it on startup)
  echo "[Desktop Entry]" >> /usr/share/applications/eclipse.desktop
  echo "Version=4.4" >> /usr/share/applications/eclipse.desktop
  echo "Name=Eclipse" >> /usr/share/applications/eclipse.desktop
  echo "Comment=Integrated Development Environment" >> /usr/share/applications/eclipse.desktop
  echo "Exec=/home/vagrant/Desktop/eclipse/eclipse -clean -data /home/vagrant/Desktop/apet_workspace" >> /usr/share/applications/eclipse.desktop
  #echo "Exec=/home/vagrant/Desktop/eclipse/eclipse" >> /usr/share/applications/eclipse.desktop 
  echo "Type=Application" >> /usr/share/applications/eclipse.desktop
  echo "Icon=/opt/eclipse/icon.xpm" >> /usr/share/applications/eclipse.desktop
  echo "Terminal=false" >> /usr/share/applications/eclipse.desktop
  echo "NoDisplay=false" >> /usr/share/applications/eclipse.desktop
  echo "Categories=Development;IDE" >> /usr/share/applications/eclipse.desktop
  chmod 777 /usr/share/applications/eclipse.desktop
  update-desktop-database 

  # Remove unused icons from sidebar (making VM as minimal as possible)
  rm -f "/usr/share/applications/ubuntu-amazon-default.desktop"
  rm -f "/usr/share/applications/libreoffice-calc.desktop"
  rm -f "/usr/share/applications/libreoffice-writer.desktop"
  rm -f "/usr/share/applications/libreoffice-impress.desktop"
  rm -f "/usr/share/applications/ubuntu-software-center.desktop"
  update-desktop-database

  chown -R vagrant: eclipse

  chown -R vagrant "/home/vagrant/Desktop"
  
  chmod -R a+rwx "/home/vagrant/Desktop"
  
  # Install Adobe Flash Player plugin to view youtube videos
  #apt-get install flashplugin-installer 

  # Add Eclipse as startup application
  # echo "+++++++++++++"
  mkdir "/home/vagrant/.config/autostart"
  mkdir "/home/vagrant/scripts"
  # echo "+++++++++++++"

  cp /usr/share/applications/eclipse.desktop /home/vagrant/.config/autostart/


  # Disable screen lock
  
  wget -O "/home/vagrant/scripts/screenlock.sh" https://github.com/SoftwareEngineeringToolDemos/FSE-2013-aPET/raw/master/build-vm/vm-contents/screenlock.sh
  
  wget -O "/home/vagrant/.config/autostart/screenlock.desktop" https://github.com/SoftwareEngineeringToolDemos/FSE-2013-aPET/raw/master/build-vm/vm-contents/screenlock.desktop
  
  chmod -R a+rwx "/home/vagrant/scripts/"
  
  reboot

  SHELL

end
