Vagrant.configure(2) do |config|

   config.vm.box = "box-cutter/ubuntu1404-desktop"

   config.vm.box_check_update = false 

   config.vm.provider "virtualbox" do |vb| 

     vb.gui = true  

     vb.memory = "2048"
  
     vb.name = "FSE-2013-aPET"

   end


   config.vm.provision "shell", inline: <<-SHELL

   add-apt-repository -y ppa:webupd8team/java

   apt-get update

       echo "oracle-java8-installer shared/accepted-oracle-license-v1-1 select true" | sudo debconf-set-selections

       apt-get install -y oracle-java8-installer

   export JAVA_HOME=/usr/lib/jvm/java-8-oracle

   source /etc/environment

   cd Desktop

   wget "https://eclipse.org/downloads/packages/release/Helios/SR2/eclipse-java-helios-SR2-linux-gtk-x86_64.tar.gz"

       tar zxvf eclipse-java-helios-SR2-linux-gtk-x86_64.tar.gz

       rm eclipse-java-helios-SR2-linux-gtk-x86_64.tar.gz
   chown -R vagrant: eclipse
   SHELL

end